services:

  #
  # The OAuth agent and API are hosted behind the API gateway
  #
  api-gateway:
    image: apigateway:1.0.0
    hostname: apigateway-internal
    ports:
      - 80:3001
    volumes:
      - ./apigateway/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:3001'
      KONG_LOG_LEVEL: 'info'
      KONG_PLUGINS: 'bundled,cors,oauth-proxy'

  #
  # The OAuth Agent is the backend for frontend component for the SPA
  #
  oauth-agent:
    image: curity/idsvr-unstable:9.2.0-d6e393af32
    hostname: bff-internal
    extra_hosts:
      - login.example.com:host-gateway
    ports:
      - 6749:6749
    volumes:
      - ../../license.json:/opt/idsvr/etc/init/license/license.json
      - ./oauthagent/config-backup.xml:/opt/idsvr/etc/init/config.xml
    environment:
      ADMIN: 'true'
      LOGGING_LEVEL: 'INFO'

  #
  # The web static content host
  #
  webhost:
    image: webhost:1.0.0
    hostname: webhost-internal
    volumes:
      - ./webhost/config.json:/usr/webhost/config.json
      - ./spa/config.json:/usr/webhost/content/config.json
    environment:
      NODE_ENV: 'production'

  #
  # The SPA accesses its API via the API gateway at http://api.example.com/api
  #
  example-api:
    image: example-api:1.0.0
    hostname: api-internal
    volumes:
      - ./api/config.json:/usr/api/config.json

  #
  # Keycloak is used as the external authorization server
  #
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    hostname: login-internal
    ports:
    - 8080:8080
    environment:
      KC_HOSTNAME_URL: 'http://login.example.com'
      KC_HOSTNAME_ADMIN_URL: 'http://login.example.com'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_HTTPS_ENABLED: 'false'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Password1
      KEYCLOAK_LOGLEVEL: DEBUG
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-dbserver
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: Password1
    command:
    - start-dev
    depends_on:
      keycloakdata:
        condition: service_healthy

  #
  # Keycloak's data includes preshipped user accounts
  #
  keycloakdata:
    image: postgres:16.3
    hostname: keycloak-dbserver
    volumes:
    - ./keycloak/data-backup.sql:/docker-entrypoint-initdb.d/data-backup.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password1
      POSTGRES_DB: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
